blog/urls.py
from django.urls import path, re_path
from django.conf.urls import handler404, handler500
from .feeds import LatestPostsFeed

from . import views

app_name='blog'

urlpatterns = [
    # post views
    path('', views.post_list, name='post_list'),
    path('tag/<slug:tag_slug>/', views.post_list, name='post_list_by_tag'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/', views.post_detail, name='post_detail'),
    path('<int:post_id>/share/', views.post_share, name='post_share'),
    path('feed/', LatestPostsFeed(), name='post_feed'),
    path('search/', views.post_search, name='post_search'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from portfolio import views
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap


sitemaps = {
    'posts': PostSitemap,
}


urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include("blog.urls", namespace='blog')),
    path('portfolio/', include("portfolio.urls", namespace='portfolio')),
    path('web/', include("web.urls", namespace='web')),
    path('sitemap.xml',
        sitemap,
        {'sitemaps': sitemaps},
        name='django.contrib.sitemaps.views.sitemap'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

portfolio/urls.py
from django.urls import path
from django.conf.urls import handler404, handler500 

from . import views

app_name='portfolio'

urlpatterns = [
    path('', views.portfolio, name='portfolio'),
]

web/urls.py
from django.urls import path
from django.conf.urls import handler404, handler500 

from . import views

app_name='web'

urlpatterns = [
    path('', views.index, name='index'),
]

web/templates/base.html
{% load static %}

<!DOCTYPE html>
<html>

  <head>
      <meta charset="utf-8">
      <title>{% block title %} Ben-David {% endblock %}</title>
      <link href="{% static 'web/css/styles.css' %}" rel="stylesheet" />
      <link href="https://fonts.googleapis.com/css?family=Merriweather|Montserrat|Sacramento" rel="stylesheet">
      <link rel="icon" href="{% static 'web/favicon.ico' %}">
      <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
  </head>

  <body>

      {% include 'navbar.html' %}

      {% block content %}
      
      {% endblock %}

      <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.min.js" integrity="sha384-mQ93GR66B00ZXjt0YO5KlohRA5SY2XofN4zfuZxLkoj1gXtW8ANNCe9d5Y3eG5eD" crossorigin="anonymous"></script>
  </body>

</html>

web/templates/navbar.html
{% load static %}

<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'web:index' %}">Ben-David</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="nav ms-auto">
            <li class="nav-item">
                <a class="nav-link active text-dark" aria-current="page" href="{% url 'portfolio:portfolio' %}">Portfolio</a>
            </li>
            <li class="nav-item">
                <a class="nav-link text-dark" href="{% url 'blog:post_list' %}">Blog</a>
            </li>
            <li class="nav-item">
                <a class="nav-link text-dark" href="#">Contect Me</a>
            </li>
            </ul>
        </div>
    </div>
</nav>