blog/urls.py
from django.urls import path, re_path
from django.conf.urls import handler404, handler500
from .feeds import LatestPostsFeed

from . import views

app_name='blog'

urlpatterns = [
    # post views
    path('', views.post_list, name='post_list'),
    path('tag/<slug:tag_slug>/', views.post_list, name='post_list_by_tag'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/', views.post_detail, name='post_detail'),
    path('<int:post_id>/share/', views.post_share, name='post_share'),
    path('feed/', LatestPostsFeed(), name='post_feed'),
    path('search/', views.post_search, name='post_search'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from portfolio import views
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap


sitemaps = {
    'posts': PostSitemap,
}


urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include("blog.urls", namespace='blog')),
    path('portfolio/', include("portfolio.urls", namespace='portfolio')),
    path('web/', include("web.urls", namespace='web')),
    path('sitemap.xml',
        sitemap,
        {'sitemaps': sitemaps},
        name='django.contrib.sitemaps.views.sitemap'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web/urls.py
from django.urls import path
from django.conf.urls import handler404, handler500 

from . import views

app_name='web'

urlpatterns = [
    path('', views.index, name='index'),
]

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from taggit.managers import TaggableManager

# Create your models here.

class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager, self).get_queryset().filter(status='published')


class Post(models.Model):
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique_for_date='publish')
    author = models.ForeignKey(User, related_name='blog_posts', on_delete=models.CASCADE)
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='draft')

    objects = models.Manager() # The default manager.
    published = PublishedManager() # The Dahl-specific manager.

    tags = TaggableManager(related_name='blog_posts')

    class Meta:
        ordering = ('-publish',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post_detail', args=[self.publish.year,
                                                 self.publish.strftime('%m'),
                                                 self.publish.strftime('%d'),
                                                 self.slug])


class Comment(models.Model):
    post = models.ForeignKey(Post, related_name='comments', on_delete=models.CASCADE)
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)
    parent = models.ForeignKey('self', null=True, blank=True, related_name='replies', on_delete=models.CASCADE)

    class Meta:
        ordering = ('created',)

    def __str__(self):
        return 'Comment by {} on {}'.format(self.name, self.post)

blog/forms.py
from django import forms
from .models import Comment

class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False, widget=forms.Textarea)


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body', 'parent')


class SearchForm(forms.Form):
    query = forms.CharField()

blog/views.py
from django.core.mail import send_mail
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Count
from django.shortcuts import get_object_or_404, redirect, render
from django.views.generic import ListView
from django.contrib.postgres.search import SearchVector

from taggit.models import Tag

from .forms import CommentForm, EmailPostForm, SearchForm
from .models import Comment, Post
from haystack.query import SearchQuerySet


def post_list(request, tag_slug=None):
    object_list = Post.published.all()
    tag = None

    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        object_list = object_list.filter(tags__in=[tag])

    paginator = Paginator(object_list, 4)  # 3 posts in each page
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver the first page.
        posts = paginator.page(1)
    except EmptyPage:
        # If page is out of range, deliver the last page of results.
        posts = paginator.page(paginator.num_pages)

    context = {
        'page': page, 
        'posts': posts, 
        'tag': tag
        }
    return render(request, 'blog/post/list.html', context)


class PostListView(ListView):
    queryset = Post.published.all()
    context_object_name = 'posts'
    paginate_by = 3
    template_name = 'blog/post/list.html'


def post_detail(request, year, month, day, post):
    post = get_object_or_404(
        Post,
        slug=post,
        status='published',
        publish__year=year,
        publish__month=month,
        publish__day=day,
    )

    comments = post.comments.filter(active=True)
    if request.method == 'POST':
        form = CommentForm(data=request.POST)
        if form.is_valid():
            parent_obj = None
            try:
                parent_id = int(request.POST.get('parent_id'))
            except:
                parent_id = None
            if parent_id:
                parent_obj = Comment.objects.get(id=parent_id)
                if parent_obj:
                    reply_comment = form.save(commit=False)
                    reply_comment.parent = parent_obj
            new_comment = form.save(commit=False)
            new_comment.post = post
            new_comment.save()
            return redirect('blog:post_detail', year=post.publish.year, month=post.publish.month, day=post.publish.day, post=post.slug)

    else:
        form = CommentForm()

    post_tags_ids = post.tags.values_list('id', flat=True)
    similar_posts = (
        Post.published
        .filter(tags__in=post_tags_ids)
        .exclude(id=post.id)
        .annotate(same_tags=Count('tags'))
        .order_by('-same_tags', '-publish')[:4]
    )

    context = {
        'post': post,
        'comments': comments,
        'comment_form': form,
        'similar_posts': similar_posts,
    }
    return render(request, 'blog/post/detail.html', context)

def post_share(request, post_id):
    post = get_object_or_404(Post, id=post_id, status='published')
    sent = False

    if request.method == 'POST':
        form = EmailPostForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = f'{cd["name"]} ({cd["email"]}) recommends you reading "{post.title}"'
            message = f'Read "{post.title}" at {post_url}\n\n{cd["name"]}\n\nComments: {cd["comments"]}'
            send_mail(subject, message, 'admin@myblog.com', [cd['to']])
            sent = True
    else:
        form = EmailPostForm()

    context = {'post': post, 'form': form, 'sent': sent}
    return render(request, 'blog/post/share.html', context)


def post_search(request):
    form = SearchForm()
    query = None
    results = []
    total_results = 0
    cd = {} 

    if 'query' in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            cd = form.cleaned_data
            query = form.cleaned_data['query']
            results = Post.objects.annotate(
                search=SearchVector('title', 'body'),).filter(search=query)
            results = SearchQuerySet().models(Post).filter(content=cd['query']).load_all()
            # count total results
            total_results = results.count()

    context = {
        'form': form, 
        'cd': cd, 
        'query': query,
        'results': results, 
        'total_results': total_results
    }
    return render(request, 'blog/post/search.html', context)

blog/templates/blog/post/detail.html
{% extends "blog/base.html" %}
{% load static %}
{% load blog_tags %}

{% block title %}{{ post.title }}{% endblock %}

{% block content %}

<section class="single-post-content">
    <div class="container">
        <div class="row">
            <div class="col-md-9 post-content" data-aos="fade-up">

                <!-- ======= Single Post Content ======= -->
                <div class="single-post">
                    <div class="post-meta"><span class="date">
                        {% for tag in post.tags.all %}
                        <a href="{% url 'blog:post_list_by_tag' tag.slug %}">{{ tag.name }}</a>
                        {% if not forloop.last %}, {% endif %}
                        {% empty %}
                            <p>No tags yet.</p>
                        {% endfor %}
                        </span> <span class="mx-1">&bullet;</span> <span>{{ post.publish }}</span>
                    </div>
                        <h1 class="mb-5">{{ post.title }}</h1>
                        {{ post.body|markdown }}
                </div>
                <!-- End Single Post Content -->

                <div>
                    <p><a href="{% url 'blog:post_share' post.id %}" class="btn btn-primary">Share this post</a></p>
                </div>
                    
                <!-- ======= Comments ======= -->
                <div class="comments">
                    {% with comments.count as total_comments %}
                        <h5 class="comment-title py-4">{{ total_comments }} comment{{ total_comments|pluralize }}</h5>
                    {% endwith %}

                    {% for comment in comments %}
                    <div class="comment d-flex mb-4">
                        <div class="flex-shrink-0">
                            <div class="avatar avatar-sm rounded-circle">
                                <img class="avatar-img" src="{% static 'blog/img/person-5.jpg' %}" alt="" class="img-fluid">
                            </div>
                        </div>
                        <div class="flex-grow-1 ms-2 ms-sm-3">
                            <div class="comment-meta d-flex align-items-baseline">
                                <h6 class="me-2">{{ comment.name }}</h6>
                                <span class="text-muted">{{ comment.created }}</span>
                            </div>
                            <div class="comment-body">
                                {{ comment.body|linebreaks }}
                            </div>
                        </div>
                    </div>
                    {% empty %}
                        <h5>There are no comments yet.</h5>
                    {% endfor %}
                </div>
                <!-- End Comments -->

                {% if new_comment %}

                <div class="alert alert-success" role="alert">
                    Your comment has been added.
                </div>

                {% else %}

                <!-- ======= Comments Form ======= -->
                <div class="row justify-content-center mt-5">
                    <div class="col-lg-12">
                    <h5 class="comment-title">Leave a Comment</h5>
                    <form method="POST" action=".">
                        {% csrf_token %}
                        <div class="row">
                            <div class="col-lg-6 mb-3">
                                <label for="comment-name">Name</label>
                                <input type="text" class="form-control" id="comment-name" name="name" placeholder="Enter your name" >
                            </div>
                            <div class="col-lg-6 mb-3">
                                <label for="comment-email">Email</label>
                                <input type="email" class="form-control" id="comment-email" placeholder="Enter your email" name="email" >
                            </div>
                            <div class="col-12 mb-3">
                                <label for="comment-message">Message</label>
                                <textarea class="form-control" id="comment-message" placeholder="Enter your message" cols="30" rows="10" name="body"></textarea>
                            </div>
                            <div class="col-12">
                                <input type="submit" class="btn btn-primary" value="Post comment">
                            </div>
                        </div>
                    </form>
                    </div>
                </div>
                <!-- End Comments Form -->

                {% endif %}

            </div>
            <div class="col-md-3">
                {% include 'blog/sidebar.html' %}
            </div>
        </div>
    </div>
</section>

{% endblock %}

<!-- ======= Single Post Content ======= -->
<div class="single-post">
    <div class="post-meta">
        <span class="date">
            {% for tag in post.tags.all %}
            <a href="{% url 'blog:post_list_by_tag' tag.slug %}">{{ tag.name }}</a>
            {% if not forloop.last %}, {% endif %}
            {% empty %}
                <p>No tags yet.</p>
            {% endfor %}
        </span>
        <span class="mx-1">&bullet;</span> <span>{{ post.publish }}</span></div>
        <h1 class="mb-5">{{ post.title }}</h1>

        {{ post.body|markdown }}

    <p><span class="firstcharacter">L</span>orem ipsum dolor sit, amet consectetur adipisicing elit. Ratione officia sed, suscipit distinctio, numquam omnis quo fuga ipsam quis inventore voluptatum recusandae culpa, unde doloribus saepe labore alias voluptate expedita? Dicta delectus beatae explicabo odio voluptatibus quas, saepe qui aperiam autem obcaecati, illo et! Incidunt voluptas culpa neque repellat sint, accusamus beatae, cumque autem tempore quisquam quam eligendi harum debitis.</p>

    <figure class="my-4">
      <img src="assets/img/post-landscape-1.jpg" alt="" class="img-fluid">
      <figcaption>Lorem ipsum dolor sit amet consectetur adipisicing elit. Explicabo, odit? </figcaption>
    </figure>
    <p>Sunt reprehenderit, hic vel optio odit est dolore, distinctio iure itaque enim pariatur ducimus. Rerum soluta, perspiciatis voluptatum cupiditate praesentium repellendus quas expedita exercitationem tempora aliquam quaerat in eligendi adipisci harum non omnis reprehenderit quidem beatae modi. Ea fugiat enim libero, ipsam dicta explicabo nihil, tempore, nulla repellendus eos necessitatibus eligendi corporis cum? Eaque harum, eligendi itaque numquam aliquam soluta.</p>
    <p>Explicabo perspiciatis, laborum provident voluptates illum in nulla consectetur atque quaerat excepturi quisquam, veniam velit ex pariatur quos consequuntur? Excepturi reiciendis perferendis, cupiditate dolorem eos illum amet. Beatae voluptates nemo esse ratione voluptate, nesciunt fugit magnam veritatis voluptas dignissimos doloribus maiores? Aliquam, dolores natus exercitationem corrupti blanditiis, consequuntur nihil nobis sed voluptatibus maiores sunt, illo provident aliquid laborum. Vitae, ut.</p>
    <p>Reprehenderit aut sed doloribus blanditiis, aspernatur magni? In molestias rem, similique ut esse repudiandae quod recusandae dolores neque earum omnis at, suscipit fuga? Minima qui veniam deserunt quisquam error amet at ratione nesciunt porro quis placeat repudiandae voluptatibus officiis fuga necessitatibus, expedita officia adipisci eaque labore accusamus? Nesciunt repellat illo exercitationem facilis similique quaerat, quis sequi? Praesentium nulla ipsam dolor.</p>
    <p>Dolorum, incidunt! Adipisci harum itaque maxime dolores doloremque porro eligendi quis, doloribus vel sit rerum sunt obcaecati nam suscipit nulla vitae alias blanditiis aliquam debitis atque illo modi et placeat. Ratione iure eveniet provident. Culpa laboriosam sed ad quia. Corrupti, earum, perferendis dolore cupiditate sint nihil maiores iusto tempora nobis porro itaque est. Ut laborum culpa assumenda pariatur et perferendis?</p>
    <p>Est soluta veritatis laboriosam, consequuntur temporibus asperiores, fugit id a ullam sed, expedita sequi doloribus fugiat. Odio et necessitatibus enim nam, iste reprehenderit cupiditate omnis ut iure aliquid obcaecati, repellendus nemo provident eveniet tempora minus! Voluptates aut laboriosam, maiores nihil accusantium, a dolorum quaerat tenetur illo eum culpa cum laudantium sunt doloremque modi possimus magni? Perferendis cum repudiandae corrupti porro.</p>
    <figure class="my-4">
      <img src="assets/img/post-landscape-5.jpg" alt="" class="img-fluid">
      <figcaption>Lorem ipsum dolor sit amet consectetur adipisicing elit. Explicabo, odit? </figcaption>
    </figure>
    <p>Quis molestiae, dolorem consequuntur labore perferendis enim accusantium commodi optio, sequi magnam ad consectetur iste omnis! Voluptatibus, quia officia esse necessitatibus magnam tempore reprehenderit quo aspernatur! Assumenda, minus dolorem repellendus corporis corrupti quia temporibus repudiandae in. Sit rem aut, consectetur repudiandae perferendis nemo alias, iure ipsam omnis quam soluta, nobis animi quis aliquam blanditiis at. Dicta nemo vero sequi exercitationem.</p>
    <p>Architecto ex id at illum aperiam corporis, quidem magnam doloribus non eligendi delectus laborum porro molestiae beatae eveniet dolor odit optio soluta dolores! Eaque odit a nihil recusandae, error repellendus debitis ex autem ab commodi, maiores officiis doloribus provident optio, architecto assumenda! Nihil cum laboriosam eos dolore aliquid perferendis amet doloremque quibusdam odio soluta vero odit, ipsa, quisquam quod nulla.</p>
    <p>Consequuntur corrupti fugiat quod! Ducimus sequi nemo illo ad necessitatibus amet nobis corporis et quasi. Optio cum neque fuga. Ad excepturi magnam quisquam ex voluptatibus vitae aut nam quidem doloribus, architecto perspiciatis sit consequatur pariatur alias animi expedita quas? Et doloribus voluptatibus perferendis qui fugiat voluptatum autem facere aspernatur quidem quae assumenda iste, sit similique, necessitatibus laborum magni. Ea, dolores!</p>
    <p>Possimus temporibus rerum illo quia repudiandae provident sed quas atque. Ipsam adipisci accusamus iste optio illo aliquam molestias? Voluptatibus, veniam recusandae facilis nobis perspiciatis rem similique, nisi ad explicabo ipsa voluptatum, inventore molestiae natus adipisci? Fuga delectus quia assumenda totam aspernatur. Nobis hic ea rem, quaerat voluptate vero illum laboriosam omnis aspernatur labore, natus ex iusto ducimus exercitationem a officia.</p>
  </div>
  <!-- End Single Post Content -->

  {% for replay in comment.replies.all %}
                            <div class="comment-replies bg-light p-3 mt-3 rounded">
                            <h6 class="comment-replies-title mb-4 text-muted text-uppercase">{{ forloop.counter }} replies</h6>

                            <div class="reply d-flex mb-4">
                                <div class="flex-shrink-0">
                                <div class="avatar avatar-sm rounded-circle">
                                    <img class="avatar-img" src="assets/img/person-4.jpg" alt="" class="img-fluid">
                                </div>
                                </div>
                                <div class="flex-grow-1 ms-2 ms-sm-3">
                                <div class="reply-meta d-flex align-items-baseline">
                                    <h6 class="mb-0 me-2">{{ replay.name }}</h6>
                                    <span class="text-muted">{{ replay.created }}</span>
                                </div>
                                <div class="reply-body">
                                    {{ replay.body }}
                                </div>
                                </div>
                            </div>
                            {% endfor %}

                            <!-- ======= Reply Form ======= -->
                            {% if comment.replies.count > 0 %}
                            <div class="row justify-content-center mt-5">
                                <div class="col-lg-12">
                                <h5 class="comment-title">Reply</h5>
                                <form method="POST" action=".">
                                    {% csrf_token %}
                                    <div class="row">
                                        <div class="col-lg-6 mb-3">
                                            <label for="comment-name">Name</label>
                                            <input type="text" class="form-control" id="comment-name" name="name" placeholder="Enter your name" >
                                        </div>
                                        <div class="col-lg-6 mb-3">
                                            <label for="comment-email">Email</label>
                                            <input type="email" class="form-control" id="comment-email" placeholder="Enter your email" name="email" >
                                        </div>
                                        <div class="col-12 mb-3">
                                            <label for="comment-message">Message</label>
                                            <textarea class="form-control" id="comment-message" placeholder="Enter your Message" cols="30" rows="10" name="body" ></textarea>
                                        </div>
                                        <div class="col-12">
                                            <input type="submit" class="btn btn-primary" value="Post comment">
                                        </div>
                                    </div>
                                </form>
                                </div>
                            </div>
                            {% endif %}
                            <!-- End Reply Form -->

blog/templates/blog/post/latest_posts.html
<!-- Latest -->
<div class="tab-pane fade" id="pills-trending" role="tabpanel" aria-labelledby="pills-trending-tab">
    <div class="post-entry-1 border-bottom">
        {% for post in recent_posts %}
        <div class="post-meta">
            <span class="date">
                {% for tag in post.tags.all %}
                <a href="{% url 'blog:post_list_by_tag' tag.slug %}">{{ tag.name }}</a>
                {% if not forloop.last %}, {% endif %}
                {% empty %}
                    <p>No tags yet.</p>
                {% endfor %}
            </span> 
            <span class="mx-1">&bullet;</span> <span>{{ post.publish }}</span>
        </div>
        <h2 class="mb-2"><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h2>
        <span class="author mb-3 d-block">{{ post.author }}</span>
        {% empty %}
        <p>No posts yet.</p>
        {% endfor %}
    </div>
</div> 
<!-- End Latest -->

blog/templates/blog/post/list.html
{% extends "blog/base.html" %}
{% load static %}
{% load blog_tags %}

{% block title %}My Blog{% endblock %}

{% block content %}

    <!-- ======= Hero Slider Section ======= -->
    <section id="hero-slider" class="hero-slider">
        <div class="container-md" data-aos="fade-in">
          <div class="row">
            <div class="col-12">
              <div class="swiper sliderFeaturedPosts">
                <div class="swiper-wrapper">
                  {% for post in posts %}
                  <div class="swiper-slide">
                    <a href="{{ post.get_absolute_url }}" class="img-bg d-flex align-items-end" style="background-image: url('{% static 'blog/img/post-slide-1.jpg' %}');">
                      <div class="img-bg-inner">
                        <h2>{{ post.title }}</h2>
                        <p>{{ post.body|markdown|truncatewords_html:30 }}</p>
                      </div>
                    </a>
                  </div>
                  {% endfor %}
                </div>
                <div class="custom-swiper-button-next">
                  <span class="bi-chevron-right"></span>
                </div>
                <div class="custom-swiper-button-prev">
                  <span class="bi-chevron-left"></span>
                </div>
  
                <div class="swiper-pagination">

                </div>
              </div>
            </div>
          </div>
        </div>
    </section>
    <!-- End Hero Slider Section -->

    
    

    {% if tag %}
        <h2 class="mb-4 display-4">Posts tagged with "{{ tag.name }}"</h2>
    {% endif %}

    <!-- ======= Post Grid Section ======= -->
<section id="posts" class="posts">
    <div class="container" data-aos="fade-up">
        <h1 class="display-4"></h1>
        <div class="section-header d-flex justify-content-between align-items-center mb-5">
            <h2>Recent Posts</h2>
            <div><a href="category.html" class="more">See All Posts</a></div>
        </div>
        <div class="row">
            <div class="col-md-9">
                {% for post in posts %}
                <div class="d-lg-flex post-entry-2">
                    <a href="{{ post.get_absolute_url }}" class="me-4 thumbnail mb-4 mb-lg-0 d-inline-block">
                        <img src="{% static 'blog/img/post-landscape-6.jpg' %}" alt="" class="img-fluid">
                    </a>
                    <div>
                        <div class="post-meta">
                            <span class="date">
                            {% for tag in post.tags.all %}
                            <a href="{% url 'blog:post_list_by_tag' tag.slug %}">{{ tag.name }}</a>
                            {% endfor %}
                            </span> 
                            <span class="mx-1">&bullet;</span> 
                            <span>{{ post.publish }}</span>
                        </div>
                        <h3><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h3>
                        <p>{{ post.body|markdown|truncatewords_html:30 }}</p>
                        <div class="d-flex align-items-center author">
                            <div class="photo"><img src="{% static 'blog/img/person-2.jpg' %}" alt="" class="img-fluid"></div>
                            <div class="name">
                                <h3 class="m-0 p-0">{{ post.author }}</h3>
                            </div>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
            <div class="col-md-3">
                {% include 'blog/sidebar.html' %}
            </div>
        </div> 
    </div>
</section>
    <!-- End Post Grid Section -->

    {% include "pagination.html" with page=posts %}
    
{% endblock %}

blog/templates/blog/post/search.html
{% extends "blog/base.html" %}
{% load static %}
{% load blog_tags %}

{% block title %}Search{% endblock %}

{% block content %}

    {% comment %} {% if "query" in request.GET %}
        <h1>Posts containing "{{ cd.query }}"</h1>
        <h3>Found {{ total_results }} result{{ total_results|pluralize }}</h3>
        {% for result in results %}
        	{% with post=result.object %}
        		<h4><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h4>
                {{ post.body|truncatewords:5 }}
        	{% endwith %}
        {% empty %}
        	<p>There are no results for your query.</p>
        {% endfor %}
        <p><a href="{% url 'blog:post_search' %}">Search again</a></p>
    {% else %}
        <h1>Search for posts</h1>
        <form action="." method="get">
            {{ form.as_p }}
            <input type="submit" value="Search">
        </form>
    {% endif %} {% endcomment %}


<!-- ======= Search Results ======= -->
<section id="search-result" class="search-result">
  <div class="container">
    <div class="row">
      <div class="col-md-9">
        {% if "query" in request.GET %}
        <h1>Posts containing "{{ cd.query }}"</h1>
        <h3>Found {{ total_results }} result{{ total_results|pluralize }}</h3>
          <h3 class="category-title">Search Results</h3>
            {% for result in results %}
              {% with post=result.object %}
              <div class="d-md-flex post-entry-2 small-img">
                <a href="single-post.html" class="me-4 thumbnail">
                  <img src="{% static 'blog/img/post-landscape-6.jpg' %}" alt="" class="img-fluid">
                </a>
                <div>
                  <div class="post-meta"><span class="date">
                    {% for tag in post.tags.all %}
                    <a href="{% url 'blog:post_list_by_tag' tag.slug %}">{{ tag.name }}</a>
                    {% endfor %}
                  </span> <span class="mx-1">&bullet;</span> 
                  <span>{{ post.publish }}</span></div>
                  <h3><a href="single-post.html">{{ post.title }}</a></h3>
                  <p>{{ post.body|truncatewords:5 }}</p>
                  <div class="d-flex align-items-center author">
                    <div class="photo"><img src="{% static 'blog/img/person-2.jpg' %}" alt="" class="img-fluid"></div>
                    <div class="name">
                      <h3 class="m-0 p-0">Wade Warren</h3>
                    </div>
                  </div>
                </div>
              </div>
                </div>
              </div>  
              {% endwith %}
              {% empty %}
        	<p>There are no results for your query.</p>
          {% endfor %}
        <p><a href="{% url 'blog:post_search' %}">Search again</a></p>
        {% else %}
        <h1>Search for posts</h1>
        <form action="." method="get">
            {{ form.as_p }}
            <input type="submit" value="Search">
        </form>
        <!-- ======= Search Form ======= -->
        <div class="search-form-wrap js-search-form-wrap">
          <form action="." method="GET" class="search-form">
            <span class="icon bi-search"></span>
            <input id="search-input" placeholder="Search" class="form-control" type="text">
            <button class="btn js-search-close"><span class="bi-x"></span></button>
          </form>
        </div>
        <!-- End Search Form -->
        {% endif %}
      </div>
    </div>
  </div>
</section> <!-- End Search Result -->

    
{% endblock %}